### ISSUE TITLE
Add support for SAM4L

### ISSUE THREAD

**Issue by john-terrell** [atsam-rs/atsam-pac#5]
SVD files can be found https://www.keil.com/dd2/pack/ under Microchip SAM4 Series Device Support and Examples.

- [ ] Make sure svd2rust generates correctly
- [ ] Add each target to top-level Cargo.toml
- [ ] Ensure doc.rs link is valid for each target mcu
- [ ] Publish to crates.io
- [ ] Ensure README.md and Cargo.toml have the correct target mcu

**Comment by haata** [comment]
Checklist for SAM4L integration

SVD files can be found https://www.keil.com/dd2/pack/ under Microchip SAM4 Series Device Support and Examples.

- [ ] Make sure svd2rust generates correctly
- [ ] Add each target to top-level Cargo.toml
- [ ] Ensure doc.rs link is valid for each target mcu
- [ ] Publish to crates.io
- [ ] Ensure README.md and Cargo.toml have the correct target mcu

**Comment by john-terrell** [comment]
Currently this is blocked on svd2rust failing to create valid output.   It creates duplicate methods that appear to be related to incorrect support for the 'derivedFrom' attribute (as on USART1).

**Comment by john-terrell** [comment]
Opened svd2rust issue rust-embedded/svd2rust#504
